---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lenovo.
--- DateTime: 2026/9/5 10:21
---
--1参数列表
--1.1优惠券id
local voucherId = ARGV[1]
--1.2用户id
local userId = ARGV[2]
--1.3订单id
local orderId = ARGV[3]

--2数据key
--2.1库存key
local stockKey = "seckill:stock:" .. voucherId
--2.2订单key
local orderKey = "seckill:order:" .. voucherId

--3脚本业务
--3.1判断库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end
--3.2判断用户是否下单
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end

--扣库存incrby
redis.call('incrby', stockKey, -1)
--下单
redis.call('sadd', orderKey, userId)
--发送消息到队列中
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId);
return 0



